[package]
name = "diamond"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
substring = { version = "1.4.5" }

rsa = "0.6.1"
rand_core = "0.6.3"
p256 = "0.11.1"
ecdsa = "0.14.3"
bech32 = { version = "0.9.0", default-features = false }
secp256k1 = { version = "0.24.0", default-features = false, features = ["bitcoin_hashes", "alloc", "rand", "rand-std", "serde" ] }

tokio = { version = "1.20.0", features = ["full"] }
